config/routes.rb
Rails.application.routes.draw do
  resources :future_recipes do
      member do
        get 'uprank'
        get'downrank'
        get 'reset_state'
        get 'set_state_done'
        get 'set_state_discarded'
      end
  end

  get 'future_recipes/add_or_update'

  get 'tags/index'

  get 'tags/create'

  get 'tags/show'

  get 'tags/update'

  get 'tags/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'categories/index'

  get 'categories/create'

  get 'categories/show'

  get 'categories/update'

  get 'categories/destroy'

  get 'welcome/index'

  root "welcome#index"

  resources :recipes do
      resources :user_ratings, only: [:new, :create, :update, :destroy]
  end

  resources :ingredients
  resources :categories
  resources :tags
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create,:edit, :update]
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/recipe.rb
#coding: utf-8
class Recipe < ActiveRecord::Base
  extend FriendlyId
 
  attr_accessor :is_recipe_component
  
  belongs_to :category
  validates :category, presence: true
  
  has_and_belongs_to_many :tags
  
  has_one :complex_ingredient, dependent: :destroy
  
  has_many :ingredient_quantity_groups, -> {order(:created_at) }, dependent: :destroy
  accepts_nested_attributes_for :ingredient_quantity_groups, 
                    allow_destroy: true,
                    reject_if: lambda { |a| a[:name].blank? }
  
  has_many :ingredient_quantities, through: :ingredient_quantity_groups
  has_many :ingredient_links, through: :ingredient_quantities
  has_many :simple_ingredients, through: :ingredient_links, 
                                source: :recipe_component, source_type: "Ingredient"
  has_many :ingredient_bases, through: :ingredient_links, source: :ingredient_base
                                

  has_many :instruction_groups, -> {order(:created_at) }, dependent: :destroy
  accepts_nested_attributes_for :instruction_groups, allow_destroy: true
  
  has_many :instructions, through: :instruction_groups
  
  has_many :links, dependent: :destroy
  accepts_nested_attributes_for :links, 
                    #reject_if: lambda { |a| a[:url].blank? && a[:name].blank? },
                    allow_destroy: true
  
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images,
                            allow_destroy: true
  
  
  validates_presence_of :description
  
  validates_presence_of :ingredient_quantity_groups
  
  validates :name, presence: true,
                   length: { minimum: 4 }



  validates :portion_count, :numericality =>true, :allow_nil => true

  has_many :user_ratings
  has_many :users, through: :user_ratings

  auto_strip_attributes :name, :description, :comments, :nullify => false, :squish => true

  friendly_id :slug_candidates, use: :slugged
  validates_presence_of :slug

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      :name,
      [:name, :category]
    ]
  end

  def should_generate_new_friendly_id?
    new_record? || slug.blank?
  end


  validate do
    logger.info "in validate now"
  end

  def sortable_name
    return name
  end
  
  def sortable_created_at
    return created_at
  end
  
  def average_rating
    avg = calc_average_rating
    if avg.nil?
      return "N/A"
    end
    
    return format_double(avg)
  end
  
  def is_recipe_component
    !complex_ingredient.nil?
  end
  
  def is_recipe_component=(value)
    logger.info("COMPLEX: YES? value = #{value}, complex = #{complex_ingredient.inspect}")
    if value == '1' && complex_ingredient.nil?
      ci = build_complex_ingredient
      ci.do_init
      logger.info ("COMPLEX: Built complex: #{ci.inspect}")
    else
      if value == '0' && !complex_ingredient.blank?
        raise "Don't support this yet"
      end
    end 
  end
  
  def sortable_category
    return category.name
  end
  
  def sortable_average_rating
    avg = calc_average_rating
    if avg.nil?
      return -1
    end
    
    return avg
  end
  
  def sortable_rating_for_user(user)
    r = user_rating(user)
    if r.blank? || r.rating.blank?
      return -1
    end
    return r.rating
  end
  
  def rating_for_user(user)
    r = user_rating(user)
    if r.blank? || r.rating.blank?
      return "N/A"
    end
    return "%g" % r.rating.to_s
  end
  
  def user_rating(user)
    logger.debug("USER_RATING: looking for rating for user #{user.name}")
    rating = user_ratings.where(user_id: user.id).first
    logger.debug("USER_RATING: found #{rating.inspect})")
    return rating
  end
  
  def total_cost
    calculate_total_cost
  end
  
  def total_kcal
    calculate_total_kcal
  end
  
  def portion_count
    self[:portion_count] || 1
  end
  
  def cost_per_portion
    total = calculate_total_cost
    if self[:portion_count].to_i == 0 || total == 0
      return "N/A"
    end
    
    per_portion = total / portion_count
    return "£%.2f" % per_portion
  end
  
  def kcal_per_portion
    total = calculate_total_kcal
    if self[:portion_count].to_i == 0
      return "N/A"
    end
    return "%.0f" % (total / portion_count)
  end
  
  def total_cost_str
    total = calculate_total_cost
    if (total == 0)
      return "N/A"
    end
    return "£%.2f" % total
  end
  
  def total_kcal_str
    total = calculate_total_kcal
    if (total == 0)
      return "N/A"
    end
    return "%d" % total
  end
  
  def self.search_by_name(query)
    where("lower(name) like lower(?)", "%#{query}%") 
  end
  
  def self.search_by_ingredient_name(query)
    select("DISTINCT recipes.*")
      .joins(:ingredient_bases)
      .where("lower(ingredient_bases.name) like lower(?)", "%#{query}%")
  end
  
  def self.search_by_ingredient_base_id(query)
    select("DISTINCT recipes.*")
      .joins(:ingredient_bases)
      .where("ingredient_bases.id= ?", "#{query}")
  end

  def self.search_by_category_id(query)
    select("DISTINCT recipes.*")
      .joins(:category)
      .where("categories.id= ?", "#{query}")
  end

  def self.search_by_updated_since(d)
    Recipe.where("updated_at > ?", d)
  end
  
  
  def self.filter_blank_instructions_from_groups(hash)
    hash = hash.with_indifferent_access
    logger.info("\n\nRECIPE_FILTER_START")
    logger.info ("RECIPE_FILTER: working on #{hash.inspect}")
    #the hash has each key/val be an instruction group
    hash.each do |group_key, group|
      logger.info("  RECIPE_FILTER: looking at group #{group.inspect}")
      
      group = InstructionGroup.filter_blank_instructions_from_group(group)
    end
    
    logger.info ("RECIPE_FILTER: returning #{hash.inspect}")
    
    return hash
  end
  
  def self.filter_blank_ingredient_quantities_from_groups(hash)
    hash = hash.with_indifferent_access
    logger.info("\n\nRECIPE_FILTER_START")
    logger.info ("RECIPE_FILTER: working on #{hash.inspect}")
    #the hash has each key/val be an iq group
    hash.each do |group_key, group|
      logger.info("  RECIPE_FILTER: looking at group #{group.inspect}")
      
      group = IngredientQuantityGroup.filter_blank_ingredient_quantities_from_group(group)
    end
    
    logger.info ("RECIPE_FILTER: returning #{hash.inspect}")
    
    return hash
  end
    
private
  
  
  def format_double(input)
    if input.blank?
      return "N/A"
    end
    return "%g" % ("%.2f" % input.to_s)
  end
  
  def calculate_total_cost
    cumulative = 0.0
    ingredient_quantity_groups.each do |iqd|
      cumulative += iqd.cost
    end
    return cumulative
  end
  
  
  def calculate_total_kcal
    cumulative = 0.0
    ingredient_quantity_groups.each do |iqd|
      cumulative += iqd.kcal
    end
    return cumulative
  end
  
  
  def calc_average_rating
    sum = 0.0
    count = 0
    user_ratings.each do |ur|
      sum = sum + ur.rating
      count = count + 1
    end
    return count == 0 ? nil : (sum / count)
  end
  
  
end

app/controllers/recipes_controller.rb
require 'will_paginate/array'

class RecipesController < ApplicationController
  before_action :setup_vars
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]

  @is_admin = false
  
  def index
    @search_ingredient_base = IngredientBase.new
    @search_category = Category.new
    @search_tag = Tag.new

    @pass_on_search_params = Hash.new
    @pass_on_sort_params = Hash.new
    
    no_search = params[:submit_search_by_recipe_name].blank? &&
                params[:submit_search_by_ingredient_name].blank? &&
                params[:submit_search_by_ingredient_base_id].blank? &&
                params[:submit_search_by_category_id].blank? &&
                params[:submit_search_by_tag_id].blank?
                
    if (no_search || !params[:submit_search_by_recipe_name].blank?) && !params[:search_by_recipe_name].blank?
      name_stripped = params[:search_by_recipe_name].strip
      @recipes = Recipe.search_by_name(name_stripped).order("created_at DESC")
      @filtered_text = "name like '%s'" % name_stripped
      @pass_on_search_params[:search_by_recipe_name] = params[:search_by_recipe_name]
    elsif (no_search || !params[:submit_search_by_ingredient_name].blank?) && !params[:search_by_ingredient_name].blank?
      name_stripped = params[:search_by_ingredient_name].strip
      @recipes = Recipe.search_by_ingredient_name(name_stripped).order("created_at DESC")
      @filtered_text = "containing ingredients like '%s'" % name_stripped
      @pass_on_search_params[:search_by_ingredient_name] = params[:search_by_ingredient_name]
    elsif (no_search || !params[:submit_search_by_ingredient_base_id].blank?) && !params[:search_by_ingredient_base_id].blank?
      @recipes = Recipe.search_by_ingredient_base_id(params[:search_by_ingredient_base_id]).order("created_at DESC")
      @search_ingredient_base = IngredientBase.find(params[:search_by_ingredient_base_id])
      @filtered_text = "containing '%s'" % @search_ingredient_base.name
      @pass_on_search_params[:search_by_ingredient_base_id] = params[:search_by_ingredient_base_id]
    elsif (no_search || !params[:submit_search_by_category_id].blank?) && !params[:search_by_category_id].blank?
      @recipes = Recipe.search_by_category_id(params[:search_by_category_id]).order("created_at DESC")
      @search_category = Category.find(params[:search_by_category_id])
      @filtered_text = "in category '%s'" % @search_category.name
      @pass_on_search_params[:search_by_category_id] = params[:search_by_category_id]
    elsif (no_search || !params[:submit_search_by_tag_id].blank?) && !params[:search_by_tag_id].blank?
      #@recipes = Recipe.search_by_tag_id(params[:search_by_tag_id]).order("created_at DESC")
      @search_tag = Tag.find(params[:search_by_tag_id])
      @recipes = @search_tag.recipes
      @filtered_text = "in tag '%s'" % @search_tag.name
      @pass_on_search_params[:search_by_tag_id] = params[:search_by_tag_id]
    else
      #@recipes = Recipe.joins(:category).order('categories.name asc, name asc')
      @recipes = Recipe.order(:created_at).reverse
    end

    @pass_on_sort_params[:sort_by] = params[:sort_by]
    @recipes = sort_by(params[:sort_by], @recipes)
    unless params[:descending].blank?
      @recipes = @recipes.reverse
    end
    @recipes = @recipes.paginate(page: params[:page])
    render 'index'
  end
  
  def sort_by(sort_field, hash)
    if sort_field.blank?
      return hash
    end
    
    symbol_sort_field = sort_field.intern
    #logger.info("instance methods of recipe: #{Recipe.instance_methods(true).inspect}")
    if !Recipe.instance_methods(true).include?(symbol_sort_field)
      logger.info("Couldn't find instance method: #{sort_field}")
      return hash
    end
    
    logger.info("SORTING ARITY: #{Recipe.instance_method(symbol_sort_field).arity}")
    arity = Recipe.instance_method(symbol_sort_field).arity
    return hash.sort_by{|item|
        if arity == 0
          item.send sort_field
        else
          item.send sort_field, current_user
        end
      }
  end
  
  def show
    @recipe = Recipe.friendly.find(params[:id])
    setup_empty_user_rating
    if !@recipe.images.empty?
      @image_to_display = @recipe.images.first
    end
  end
  
  def edit
    @recipe = Recipe.friendly.find(params[:id])
    setup_empty_user_rating
  end
  
  def update
#    render plain: params[:recipe].inspect
    
    @recipe = Recipe.friendly.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end
  
  def destroy
    @recipe = Recipe.friendly.find(params[:id])
    @recipe.destroy
   
    redirect_to recipes_path
  end

  def new
    #we create an empty recipe here so that there is always a 'recipe' variable available to the template
    @recipe = Recipe.new
    @is_component = false
    
    ur = @recipe.user_ratings.build(user_id: current_user.id)
    
    ingredient_group = @recipe.ingredient_quantity_groups.build(name: "Default")
    ingredient_group.ingredient_quantities << IngredientQuantity.new
    
    instruction_group = @recipe.instruction_groups.build(name: "Default")
    instruction_group.instructions << Instruction.new
  end
  
  def create
    #render plain: params[:recipe].inspect
 
    p = recipe_params
    begin
      @recipe = Recipe.new(p)
    rescue
      flash[:danger] = "Failed to create recipe"
      @recipe = Recipe.new
      render 'new'
      return
    end
    #if @is_component
    #  ci = @recipe.build_complex_ingredient
    #  ci.build_ingredient_link
    #  logger.info("COMPLEX: built complex: #{@recipe.complex_ingredient.inspect}")
    #end 
    
    if @recipe.save
      redirect_to @recipe
    else
      logger.info("COMPLEX: redirect, is_component = #{@is_component}")
      render 'new'
    end
    
  end
  
  private
    def recipe_params
      ret_params = params.require(:recipe)
        .permit(:name, :description, :comments, :category_id, :total_time, :active_time, 
                  :is_recipe_component, :cooking_time, :portion_count, { tag_ids:[] }, :_destroy,
                links_attributes: [:id, :description, :url, :_destroy],
                images_attributes: [:id, :description, :url, :_destroy],
                instruction_groups_attributes: [
                  :id,
                  :name,
                  :_destroy,
                  {:instructions_attributes => [
                    :id,
                    :step_number, 
                    :details,
                    :_destroy]
                  }
                ],
                ingredient_quantity_groups_attributes: [
                  :id,
                  :name,
                  :_destroy,
                  {:ingredient_quantities_attributes => [
                      :id, 
                      :quantity, 
                      :preparation,
                      :ingredient_name,
                      :ingredient_link_id,
                      {:ingredient => [:name, :id]},
                      {:ingredient_attributes => [:name, :id]},
                      :_destroy]
                    }
                  ]
                )
      if ret_params.has_key?("instruction_groups_attributes")
        instruction_groups = ret_params["instruction_groups_attributes"]
        
        instruction_groups = Recipe.filter_blank_instructions_from_groups(instruction_groups)
        
        ret_params["instruction_groups_attributes"] = instruction_groups;
      end

      if ret_params.has_key?("ingredient_quantity_groups_attributes")
        iq_groups = ret_params["ingredient_quantity_groups_attributes"]
        
        iq_groups = Recipe.filter_blank_ingredient_quantities_from_groups(iq_groups)
        
        ret_params["ingredient_quantity_groups_attributes"] = iq_groups
      end

      logger.info(ret_params)
      return ret_params
      
    end
    
  def setup_vars
    @sortable_table = 1
    @is_admin = current_user && current_user.is_admin?
  end
  
  def setup_empty_user_rating
    return unless current_user
    logger.info("USER_RATING: doing user rating stuff")
    @user_rating = @recipe.user_rating(current_user)
    logger.info("USER_RATING: found #{@user_rating.inspect}")
    return unless @user_rating.blank?
    
    logger.info("USER_RATING: creating new empty rating")
    @user_rating = UserRating.new(user: current_user, recipe: @recipe)
    logger.info("USER_RATING: created #{@user_rating}")
    #@recipe.user_ratings << @user_rating
    #@recipe.reload
    #logger.info("USER_RATING: created #{@recipe.user_rating(current_user).inspect}")
  end
  
  # Confirms an admin user.
  def admin_user
    unless @is_admin
      flash[:danger] = "Must be admin to modify recipes"
      redirect_to(recipes_url) 
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_table.html.erb
<%= will_paginate @recipes%>
<table class='gridtable'>
  <tr>
  	<%if @sortable_table%>
  	<th style='width:10%'><%= link_to 'Created',
  									recipes_path(@pass_on_search_params.merge(:sort_by => 'sortable_created_at'))%></th>
    <th style='width:20%'><%= link_to 'Name',
    								recipes_path(@pass_on_search_params.merge(:sort_by => 'sortable_name'))%></th>
    <th style='width:40%'>Description</th>
    <th style='width:10%'><%= link_to 'Category',
    								recipes_path(@pass_on_search_params.merge(:sort_by => 'sortable_category'))%></th>
    <th style='width:5%'><%= link_to 'Average Rating',
    								recipes_path(@pass_on_search_params.merge(:sort_by => 'sortable_average_rating', :descending => '1'))%></th>
    <% if @current_user %>
    <th style='width:5%'><%= link_to 'Your Rating',
    								recipes_path(@pass_on_search_params.merge(:sort_by => 'sortable_rating_for_user', :descending => '1'))%></th>
    <%end%>
    <%else%>
    <th style='width:10%'><%=@time_type%></th>
    <th style='width:20%'>Name</th>
    <th style='width:40%'>Description</th>
    <th style='width:10%'>Category</th>
    <th style='width:5%'>Average Rating</th>
    <% if @current_user %>
    <th style='width:5%'>Your Rating</th>    
    <%end%>
    <%end%>
    <th style='width:5%'>Total Time</th>
    <th style='width:5%'>Cost Per Portion</th>
  </tr>
 
  <% @recipes.each do |recipe| %>
    <tr>
   	  <td><%= @time_type == "Last Updated" ? recipe.updated_at.strftime("%F") : recipe.created_at.strftime("%F") %></td>
      <td><%= link_to recipe.name, recipe_path(recipe) %></td>
      <td><%= recipe.description %></td>
      <td><%if recipe.category%>
      		<%= link_to recipe.category.name, 
      					recipes_path(:search_by_category_id => recipe.category.id,
      								 :submit_search_by_category_id => '1')  %>
          <%end%>
      </td>
      <td><%= recipe.average_rating %></td>
      <% if @current_user %>
      <td><%= recipe.rating_for_user(@current_user)%></td>
      <%end%>
      <td><%= recipe.total_time %></td>
      <td><%= recipe.cost_per_portion %></td>
    <% if @is_admin %>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      <td><%= link_to 'Delete', recipe_path(recipe),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    </tr>
  <% end %>
</table>


<%= will_paginate @recipes %>

app/views/recipes/edit.html.erb
<h1>Editing '<%= @recipe.name -%>' (<%= link_to "Cancel", recipe_path(@recipe) -%>)</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>
	<%if !@filtered_text.blank?%>
Filtered Recipes: <%=@filtered_text%>
<%else%>
All Recipes
<%end%>
	</h1>
 <%= form_tag(recipes_path, :method => "get", id: "search-form") do %>
   <%= hidden_field_tag :sort_by, params[:sort_by] %>
 <div class='boxed_table'>
  <table>
 	<tr>
 		<td>
 			Filter by Name:
 		</td>
		<td>
 			<%= text_field_tag :search_by_recipe_name, 
 							params[:search_by_recipe_name], 
 							placeholder: "Search Recipes by Name", 
 							:autocomplete => :off %>
		</td>
		<td>
			<%= submit_tag "Search", :name => 'submit_search_by_recipe_name' %>
		</td>
 	</tr>
 	<tr>
 		<td>
 			Filter by Ingredient:
 		</td>
		<td>
			<%= text_field_tag :search_by_ingredient_name, 
								params[:search_by_ingredient_name], 
								placeholder: "Search Recipes by Ingredient", 
								:autocomplete => :off %>
		</td>
		<td>
			<%= submit_tag "Search", :name => 'submit_search_by_ingredient_name' %>
		</td>
 	</tr>
 	<tr>
 		<td align='right'>Or Exact:</td>
 		<td align='right'>
		<%= select_tag(:search_by_ingredient_base_id, 
							options_from_collection_for_select(
								IngredientBase.order_by_name, 
								:id, :name, @search_ingredient_base.id),
							:prompt => '<Select an Ingredient>'
							) %>
		</td>
		<td>
			<%= submit_tag "Search", :name => 'submit_search_by_ingredient_base_id' %>
		</td>
 	</tr>
 	 <tr>
 		<td>
 			Filter by Category:
 		</td>
		<td align='right'>
			<%= select_tag(:search_by_category_id, 
							options_from_collection_for_select(
								Category.order("name"), 
								:id, :name, @search_category.id),
							:prompt => '<Select a Category>'
							) %>
		</td>
		<td>
			<%= submit_tag "Search", :name => 'submit_search_by_category_id' %>
		</td>
 	</tr>
 	<tr>
 		<td>
 			Filter by Tag
 		</td>
		<td align='right'>
			<%= select_tag(:search_by_tag_id, 
							options_from_collection_for_select(
								Tag.order("name"), 
								:id, :name, @search_tag.id),
							:prompt => '<Select a Tag>'
							) %>
		</td>
		<td>
			<%= submit_tag "Search", :name => 'submit_search_by_tag_id' %>
		</td>
 	</tr>
 </table>
 
 <%= link_to 'Clear Filters', recipes_path %>
 </div>
<%end%>
 
<% if @is_admin %>
  <p>
 <%= link_to 'Add recipe', new_recipe_path %>
 </p>
<% end %>

<%= render 'table' %>

app/views/recipes/show.html.erb
<h1 class='h1-smaller-margin'><%= @recipe.name %> 
	<%if @is_admin%>(<%= link_to 'Edit', edit_recipe_path(@recipe) %>)<%end%>
	</h1>

<% if @recipe.category %>
	<%= link_to @recipe.category.name,
      			recipes_path(:search_by_category_id => @recipe.category.id),
      			:class => 'category_tag'
      			%><br/>
<%end%>

<% if @recipe.tags.count > 0%>
<p>
	<% @recipe.tags.each do |tag|%>
		<%= link_to tag.name,
      			recipes_path(:search_by_tag_id => tag.id),
      			:class => 'tag_tag'
      			%>
    <%end%>
</p>
<%end%>

<p>
  <%= @recipe.description %>
</p>

<%if !@image_to_display.blank? %>
<!--<iframe src="<%=@image_to_display.url%>/player/" width="75" height="75" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>-->
<%= image_tag @image_to_display.url%> <!--, size: "400x200" -->

<%end%>

<%if @recipe.is_recipe_component%>
<p>
This recipe is a component recipe and is used in 
		<%= link_to @recipe.complex_ingredient.ingredient_link.recipes_count,
      			recipes_path(:search_by_ingredient_base_id => @recipe.complex_ingredient.ingredient_link.ingredient_base.id)
     	%>
     	other recipes.
</p>
<%end%>

<% if @recipe.links.any? %>
<div id="related_links">
	<strong>Links:</strong><br/>
	<ul >
	<% @recipe.links.each do |link| %>
	 <li><%= link_to link.description, link.url, :target=> '_blank' %></li>
	<% end %>
	</ul>
</div>
<%end%>

<p>
	<% if !@recipe.total_time.blank? %>
Total Time: <%= @recipe.total_time || "N/A" %><br/>
	<%end%>
	<% if !@recipe.active_time.blank? %>
Active Time: <%= @recipe.active_time || "N/A" %><br/>
	<%end%>
	<% if !@recipe.cooking_time.blank? %>
Cooking Time: <%= @recipe.cooking_time || "N/A" %><br/>
	<%end%>
</p>
</br>
<p>
	Average Rating: <%= @recipe.average_rating %>
</p>	
	<%if @current_user%><br/>
		<%= form_for ([@recipe, @user_rating]) do |f| %>
			<%= f.hidden_field :user_id, :value => @current_user.id%>
			
			Your Rating: <%= f.text_field :rating , size:"3", :autocomplete => :off %></br>
			<%= f.submit "Update Rating" %>
		<%end%>
		
		<%if !@user_rating.rating.blank?%>
			<%= form_for ([@recipe, @user_rating]), method: :delete do |f| %>
				<%= f.submit "Delete Rating" %>
			<%end%>
		<%end%>
	<%end%>
</br>

<p>
	Number of Portions: <%= @recipe.portion_count || "N/A" %>
</p>

<table class='gridtable'>
	<caption>Fact Sheet</caption>
	<thead>
		<tr>
			<th></th>
			<th>Total</th>
			<th>Per Portion</th>
		</tr>
	</thead>
	<tr>
		<td>Cost</td>
		<td><%= @recipe.total_cost_str %></td>
		<td><%= @recipe.cost_per_portion %></td>
	</tr>
	<tr>
		<td>KCal</td>
		<td><%= @recipe.total_kcal_str %></td>
		<td><%= @recipe.kcal_per_portion %></td>
	</tr>
</table>

<div id='ingredients_div'>
	<table class='gridtable'>
		<caption>Ingredients</caption>
		<thead>
			<tr>
				<th>Quantity</th>
				<th>Ingredient</th>
				<th>Cost</th>
				<th>KCal</th>
			<tr>
		</thead>
			
    <% @recipe.ingredient_quantity_groups.each do |iqd| %>
        <%if @recipe.ingredient_quantity_groups.count > 1 %>
        	<tr>
        		<td colspan="4" class='bold_centered'><%= iqd.name %></td>
      		</tr>
      	<%end%>
		<% iqd.ingredient_quantities.each do |ingredient_quantity| %>
		<tr>
			<td><%= ingredient_quantity.quantity_description %></td>
			
			<% if ingredient_quantity.ingredient_link.linkable? %>
			    <td><%= link_to ingredient_quantity.prepared_ingredient_description, recipe_path(ingredient_quantity.ingredient_link.complex_ingredient.recipe) 
			    	%></td>
			<%else%>
			<td><%= ingredient_quantity.prepared_ingredient_description %></td>
			<%end%>
			
			<td><%= ingredient_quantity.cost_as_str %></td>
			<td><%= ingredient_quantity.kcal_as_str %></td>
		</tr>
		<%end%>
	<% end %>
	</table>
</div>
</br>
<div id='instructions_div'>
	<table class='gridtable'>
	<caption>Instructions</caption>
	<thead>
		<tr>
			<th>Step #</th>
			<th>Instruction</th>
		<tr>
	</thead>
	<% @recipe.instruction_groups.each do |ig| %>
        <%if @recipe.instruction_groups.count > 1 %>
    	<tr>
    		<td colspan="3" class='bold_centered'><%= ig.name %></td>
  		</tr>
      	<%end%>
      	
		<% ig.instructions.each do |instruction| %>
		<tr>
			<td><%= instruction.step_number %></td>
			<td style="white-space: pre-wrap;"><%= instruction.details %></td>
		</tr>
		<%end%>
	<% end %>
	</table>
</div>

<%if !@recipe.comments.blank?%>
<h2>Comments</h2>
<div class='display_box'>
<%= simple_format(@recipe.comments) %>
</div>
<%end%>