config/routes.rb
Rails.application.routes.draw do
  resources :future_recipes do
      member do
        get 'uprank'
        get'downrank'
        get 'reset_state'
        get 'set_state_done'
        get 'set_state_discarded'
      end
  end

  get 'future_recipes/add_or_update'

  get 'tags/index'

  get 'tags/create'

  get 'tags/show'

  get 'tags/update'

  get 'tags/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'categories/index'

  get 'categories/create'

  get 'categories/show'

  get 'categories/update'

  get 'categories/destroy'

  get 'welcome/index'

  root "welcome#index"

  resources :recipes do
      resources :user_ratings, only: [:new, :create, :update, :destroy]
  end

  resources :ingredients
  resources :categories
  resources :tags
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create,:edit, :update]
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/ingredient.rb
#coding: utf-8
class Ingredient < ActiveRecord::Base
  has_one :ingredient_link, as: :recipe_component, dependent: :destroy, autosave: true
  validates :ingredient_link, presence: true
  
  belongs_to :measurement_type
  validates :measurement_type, presence: true
  
  has_one :ingredient_base, through: :ingredient_link
  
  has_many :ingredient_quantities, through: :ingredient_link
  has_many :ingredient_quantity_groups, through: :ingredient_quantities
  has_many :recipes, through: :ingredient_quantity_groups
                      
                   
  validates :cost_basis, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :kcal_basis, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cost, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :kcal, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  
  auto_strip_attributes :cost_note, :kcal_note, :nullify => false, :squish => true

  def editable?
    true
  end
  def linkable?
    false
  end
  
  #used during construction - map to the ingredient base
  def name=(n)
    logger.info "HELLO"
 
    if ingredient_link.nil?
      self.build_ingredient_link
      ingredient_link.recipe_component = self
    end
    ingredient_link.ingredient_base = IngredientBase.find_or_create_by!(name: n)
   end
  
  def name
    if ingredient_base.nil?
      ""
    else
      ingredient_base.name
    end
  end
  
  def cost_for_quantity(qty)
    if cost_basis.to_i == 0 || cost.nil?
        logger.error "CALC_COST: ingredient #{name} has zero values"
        return 0
      end
      
      logger.debug "CALC_COST: ingredient #{name}, unit #{cost_basis}, cost #{cost}"
      units_used = qty / cost_basis.to_f
      
      return units_used * cost
  end
  
  def kcal_for_quantity(qty)
    if kcal_basis.to_i == 0 || kcal.nil?
        logger.error "CALC_KCAL: ingredient #{name} has zero values"
        return 0
      end
      
      logger.debug "CALC_KCAL: ingredient #{name}, unit #{kcal_basis}, kcal #{kcal}"
      units_used = qty / kcal_basis.to_f
      return units_used * kcal
  end
  
  def measurement_type_str
    measurement_type ? measurement_type.measurement_type : "N/A"
  end
  
  def basis_str(basis)
    if measurement_type.measurement_type == "By Quantity"
      if basis == 1
        return " each"
      else
        return " for #{basis}"
      end
    end
    return " / #{basis}#{measurement_type.measurement_name}"
  end
  
  def cost_str
    if cost > 0
      formatted_cost = "%.2f" % cost
    
      formatted = "#{formatted_cost}#{basis_str(cost_basis)}"
    else
      formatted = "0"
    end
    
    if !cost_note.blank?
      return "£#{formatted} (#{cost_note})"
    else
      return "£#{formatted}"
    end
  end

  def kcal_str
    if kcal > 0
      formatted = "#{kcal}#{basis_str(kcal_basis)}"
    else
      formatted = "0"
    end
    
    if !kcal_note.blank?
      return "#{formatted} (#{kcal_note})"
    else
      return "#{formatted}"
    end
  end
  
  
  def description_in_recipe
    if !measurement_type.measurement_name.blank?
      "#{name} (#{measurement_type.measurement_name})"
    else
      "#{name}"
    end
  end

private
    
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :admin_user, only: [:edit, :update, :destroy]

  @is_admin = false
  
  def index
    setup_vars
    @simple_ingredient_bases = IngredientBase.simples_ordered_by_name
    @complex_ingredient_bases = IngredientBase.complex_ordered_by_name
    
    @ingredient = Ingredient.new
    @ingredient.ingredient_link = IngredientLink.new
    @ingredient.ingredient_link.ingredient_base = IngredientBase.new
    
    logger.info "Created ingredient, looks like #{@ingredient.inspect}"
  end  
  
  def create
    #render plain: params[:recipe].inspect
    logger.info("params: #{params.inspect}")
    setup_vars

    name = params[:name]
    
    @ingredient = Ingredient.new(ingredient_params)
    
    if @ingredient.save
      redirect_to action: "index"
    else
      @simple_ingredient_bases = IngredientBase.simples_ordered_by_name
      @complex_ingredient_bases = IngredientBase.complex_ordered_by_name
      render 'index'
    end
  end
  
  def show
    setup_vars
    @simple_ingredient_bases = IngredientBase.simples_ordered_by_name
    @complex_ingredient_bases = IngredientBase.complex_ordered_by_name
    @ingredient = Ingredient.find(params[:id])
    render 'index'
  end
  
  def update
    setup_vars
#    render plain: params[:recipe].inspect
    
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path
    else
      @simple_ingredient_bases = IngredientBase.simples_ordered_by_name
      @complex_ingredient_bases = IngredientBase.complex_ordered_by_name
      render 'index'
    end
  end
  
  def destroy
    setup_vars
    @deleted_ingredient = Ingredient.find(params[:id])
    name = @deleted_ingredient.name
    if @deleted_ingredient.destroy
      #redirect_to ingredients_path
      message = name + " deleted successfully"
      redirect_to ingredients_path, :notice => message
    else
      message = name + " couldn't be deleted; it still has recipes"
      redirect_to ingredients_path, :alert => message
      #@ingredients = Ingredient.order(:name)
      #@ingredient = Ingredient.new
      #render 'index'
    end
   
  end
  
private
  def setup_vars
    @is_admin = current_user && current_user.is_admin?
  end

  def ingredient_params
    return params.require(:ingredient).permit(:name, :measurement_type_id, 
                                                  :cost_basis, :cost, :cost_note,
                                                  :kcal_basis, :kcal, :kcal_note)
  end
  
  
  # Confirms an admin user.
  def admin_user
    unless logged_in? && current_user.is_admin?
      flash[:danger] = "Must be admin to modify ingredients"
      redirect_to(ingredients_url) 
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

 <% if @ingredient.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited
      this ingredient from being updated:</h2>
    <ul>
    <% @ingredient.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% else %>
  
  <% end %>
  
  <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    
<% if @is_admin %>
    
<%= form_for @ingredient do |f| %>
  <p>
    <%= f.text_field :name, :autocomplete => :off %>
    <%= f.collection_select(:measurement_type_id, 
								MeasurementType.all, 
								:id, :measurement_type, :prompt => '<Select a Measurement Type>') %>
	<br/>
	<table>
	 	<tr>
	 		<td><%= f.label :cost_basis %></td>
	 		<td><%= f.text_field :cost_basis, :size => 4, :autocomplete => :off %></td>
            <td><%= f.label :cost %></td>
            <td><%= f.text_field :cost, :size => 4, :autocomplete => :off %></td>
	 		<td><%= f.label :cost_note, "Note" %></td>
	 		<td><%= f.text_field :cost_note, :size => 25, :autocomplete => :off %></td>
	 	</tr>
	 	<tr>
	 		<td><%= f.label :kcal_basis %></td>
	 		<td><%= f.text_field :kcal_basis, :size => 4, :autocomplete => :off %></td>
            <td><%= f.label :kcal %></td>
            <td><%= f.text_field :kcal, :size => 4, :autocomplete => :off %></td>
	 		<td><%= f.label :kcal_note, "Note" %></td>
	 		<td><%= f.text_field :kcal_note, :size => 25, :autocomplete => :off %></td>
	 	</tr>
	</table>
	<br/>
    <%= f.submit %>
  </p>
<% end %>


<% end %>
  
<table class='gridtable'>
  <tr>
    <th>Name</th>
    <th>Measurement</th>
    <th>Cost (£)</th>
    <th>KCal</th>
    <th># Recipes</th>
  </tr>
  
  <% @simple_ingredient_bases.each do |ib|%>
  <%first = 1%>
  
  	<% ib.ingredient_links.each do |ingredient_link| %>
  <tr>
  	<%if first == 1%>
 	<td rowspan='<%=ib.ingredient_links.count %>'>
 		<%= ib.name%> 
 	</td>
 	<%end%>

    <td><%= ingredient_link.measurement_type_str %></td>
    <td><%= ingredient_link.cost_str %></td>
    <td><%= ingredient_link.kcal_str %></td>
    <%if first == 1%>
  	  <%first = 0%>
    <td rowspan="<%=ib.ingredient_links.count %>">
    	<%= link_to ib.recipes_count,
      			recipes_path(:search_by_ingredient_base_id => ib.id)%>
	</td>
	<%end%>

	<%if @is_admin %>
      <td><%= link_to 'Edit', ingredient_path(ingredient_link.ingredient) %></td>
      <td><%= link_to 'Delete', ingredient_path(ingredient_link.ingredient),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<%end%>
  </tr>
  <% end %>
  <%end%>

  <% @complex_ingredient_bases.each do |ib| %>
  	<% ib.ingredient_links.each do |ingredient_link| %>
    <tr>
      <td><%= link_to ingredient_link.name, recipe_path(ingredient_link.complex_ingredient.recipe)%></td>
      <td><%= ingredient_link.measurement_type_str %></td>
      <td><%= ingredient_link.cost_str %></td>
      <td><%= ingredient_link.kcal_str %></td>
      <td><%= link_to ingredient_link.recipes_count,
      			recipes_path(:search_by_ingredient_base_id => ib.id)%></td>

      <td></td>
      <td></td>
    </tr>
    <%end%>
  <% end %>
</table>