config/routes.rb
Rails.application.routes.draw do
  resources :future_recipes do
      member do
        get 'uprank'
        get'downrank'
        get 'reset_state'
        get 'set_state_done'
        get 'set_state_discarded'
      end
  end

  get 'future_recipes/add_or_update'

  get 'tags/index'

  get 'tags/create'

  get 'tags/show'

  get 'tags/update'

  get 'tags/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'categories/index'

  get 'categories/create'

  get 'categories/show'

  get 'categories/update'

  get 'categories/destroy'

  get 'welcome/index'

  root "welcome#index"

  resources :recipes do
      resources :user_ratings, only: [:new, :create, :update, :destroy]
  end

  resources :ingredients
  resources :categories
  resources :tags
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create,:edit, :update]
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/future_recipe.rb
#coding: utf-8
class FutureRecipe < ActiveRecord::Base
  validates :name, presence: true
  validates :link, presence: true, uniqueness: true
  
  validate :valid_url, :link_not_in_recipes
  
  belongs_to :category
  validates :category, presence: true
  
      
  has_and_belongs_to_many :tags

  auto_strip_attributes :name, :link, :description, :nullify => false, :squish => true

  enum state: [ :pending, :done, :discarded ]

  def get_link_source
    #if the link doesn't have http:// in front then start it with that - deals with historic issues, validation stops/fixes it now
    if not link.starts_with?('http')
      link.insert(0, "http://")
    end
    URI.parse(link).host.sub(/\Awww\./, '')
  end
  
  def get_state
    logger.info("state is now #{state}")
    state or "UNKNOWN"
  end

  def valid_url
    if not link.starts_with?('http')
      link.insert(0, "http://")
    end
    uri = URI.parse(link)
    if not uri.kind_of?(URI::HTTP)
      errors.add(:link, "Not a HTTP link")
    end
  rescue URI::InvalidURIError
    errors.add(:link, "not valid")
  end

  def link_not_in_recipes
    if self.persisted?
      return
    end
    
    links = Link.where("url = ?", link)
    if not links.empty?
      existing = links[0]
      logger.info("LINK: Found link already exists in recipe: #{links[0].recipe.name}")
      errors.add(:link, "Found link already exists in recipe: #{links[0].recipe.name}")
    end
  end
  
  
  def sortable_name
    return name
  end
  
  def sortable_category
    return category.name
  end
  
  def sortable_updated_at
    return updated_at
  end

  def sortable_created_at
    return created_at
  end
  
  def sortable_website
    return get_link_source()
  end

  def sortable_rank
    return rank
  end
  
  def self.search_by_name(query)
    where("lower(name) like lower(?)", "%#{query}%") 
  end
  
  def self.search_by_category_id(query)
    select("DISTINCT future_recipes.*")
      .joins(:category)
      .where("categories.id= ?", "#{query}")
  end
  
  def self.search_by_website(query)
    where("link like ?", "%#{query}%")
    #initial = where("link like ?", "%#{query}%")
    #initial.select{|fr| fr.get_link_source =~ /#{query}/}
  end
  
  
end

app/controllers/future_recipes_controller.rb
require 'will_paginate/array'
class FutureRecipesController < ApplicationController
  before_action :setup_vars
  before_action :set_future_recipe, only: [:show, :edit, :update, :destroy, :uprank, :downrank, :set_state_done, :set_state_discarded, :reset_state]
  
  before_action :admin_user
  skip_before_action :admin_user, only: [:index, :show, :sort_by]
  
  @is_admin = false
  
  # GET /future_recipes
  # GET /future_recipes.json
  def index
    @search_category = Category.new
    @search_tag = Tag.new
    
    @pass_on_search_params = Hash.new
    @pass_on_sort_params = Hash.new

    no_search = params[:submit_search_by_future_recipe_name].blank? &&
                params[:submit_search_by_website].blank? &&
                params[:submit_search_by_category_id].blank? &&
                params[:submit_search_by_tag_id].blank?
    
    include_done = params[:include_done] == "1"
    include_discarded = params[:include_discarded] == "1"
        
    if (no_search || !params[:submit_search_by_future_recipe_name].blank?) && !params[:search_by_future_recipe_name].blank?
      name_stripped = params[:search_by_future_recipe_name].strip
      @future_recipes = FutureRecipe.search_by_name(name_stripped).order("created_at DESC")
      @filtered_text = "name like '%s'" % name_stripped
      @pass_on_search_params[:search_by_future_recipe_name] = params[:search_by_future_recipe_name]
    elsif (no_search || !params[:submit_search_by_website].blank?) && !params[:search_by_website].blank?
      name_stripped = params[:search_by_website].strip
      @future_recipes = FutureRecipe.search_by_website(name_stripped).order("created_at DESC")
      @filtered_text = "website like '%s'" % name_stripped
      @pass_on_search_params[:search_by_website] = params[:search_by_website]

    elsif (no_search || !params[:submit_search_by_category_id].blank?) && !params[:search_by_category_id].blank?
      @future_recipes = FutureRecipe.search_by_category_id(params[:search_by_category_id]).order("created_at DESC")
      @search_category = Category.find(params[:search_by_category_id])
      @filtered_text = "in category '%s'" % @search_category.name
      @pass_on_search_params[:search_by_category_id] = params[:search_by_category_id]

    elsif (no_search || !params[:submit_search_by_tag_id].blank?) && !params[:search_by_tag_id].blank?
      @search_tag = Tag.find(params[:search_by_tag_id])
      @future_recipes = @search_tag.future_recipes.order(:created_at).reverse
      @filtered_text = "in tag '%s'" % @search_tag.name
      @pass_on_search_params[:search_by_tag_id] = params[:search_by_tag_id]

    else
      @future_recipes = FutureRecipe.order(:created_at).reverse
    end

    if not include_done or not include_discarded
      @future_recipes = @future_recipes.select{|fr| fr.state == "pending" || (include_done && fr.state == "done") || (include_discarded && fr.state == "discarded")}
#      @future_recipes = @future_recipes.where("state =pending")
    end
    
    @pass_on_sort_params[:sort_by] = params[:sort_by]
    @future_recipes = sort_by(params[:sort_by], @future_recipes)
    unless params[:descending].blank?
      @future_recipes = @future_recipes.reverse
    end
    @future_recipes = @future_recipes.paginate(page: params[:page])
    render 'index'
  end

  def sort_by(sort_field, hash)
    if sort_field.blank?
      return hash
    end
    
    symbol_sort_field = sort_field.intern
    #logger.info("instance methods of recipe: #{Recipe.instance_methods(true).inspect}")
    if !FutureRecipe.instance_methods(true).include?(symbol_sort_field)
      logger.info("Couldn't find instance method: #{sort_field}")
      return hash
    end
    
    logger.info("SORTING ARITY: #{FutureRecipe.instance_method(symbol_sort_field).arity}")
    arity = FutureRecipe.instance_method(symbol_sort_field).arity
    return hash.sort_by{|item|
        if arity == 0
          item.send sort_field
        else
          item.send sort_field, current_user
        end
      }
  end

  # GET /future_recipes/1
  # GET /future_recipes/1.json
  def show
  end
  
  # GET /future_recipes/new
  def new
    link = ""
    if (!params["new_link"].blank?)
      link = params["new_link"].strip
    end
    
    if !link.blank?
      #does it already exist?
      logger.info("checking if #{link} already exists")
      existing = FutureRecipe.find_by_link(link)
      if existing
        redirect_to edit_future_recipe_path(:id => existing)
      end
    end
    
    @future_recipe = FutureRecipe.new
    @future_recipe.link = link
  end

  # GET /future_recipes/1/edit
  def edit
  end

  # POST /future_recipes
  # POST /future_recipes.json
  def create
    @future_recipe = FutureRecipe.new(future_recipe_params)

    respond_to do |format|
      if @future_recipe.save
        
        format.html { redirect_to future_recipes_path, notice: 'Future link was successfully created.' }
        format.json { redirect_to future_recipes_path, status: :created, location: @future_recipe }
      else
        format.html { render :new }
        format.json { render json: @future_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /future_recipes/1
  # PATCH/PUT /future_recipes/1.json
  def update
    respond_to do |format|
      if @future_recipe.update(future_recipe_params)
        format.html { redirect_to @future_recipe, notice: 'Future link was successfully updated.' }
        format.json { render :show, status: :ok, location: @future_recipe }
      else
        format.html { render :edit }
        format.json { render json: @future_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /future_recipes/1
  # DELETE /future_recipes/1.json
  def destroy
    @future_recipe.destroy
    respond_to do |format|
      format.html { redirect_to future_recipes_url, notice: 'Future link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reset_state
    set_state(:pending)
  end

  def set_state_done
    set_state(:done)
  end

  def set_state_discarded
    set_state(:discarded)
  end

  def uprank
    @future_recipe.rank = @future_recipe.rank + 1
    
      if @future_recipe.save
        redirect_to future_recipes_path(request.parameters)
      else
        redirect_to future_recipes_url, notice: 'Couldnt uprank!'
      end

    #respond_to do |format|
     # if @future_recipe.save
        #format.html { redirect_to future_recipes_url, notice: 'Future link was successfully upranked.' }
    #    redirect_to future_recipes_path(request.parameters)

        #format.html { redirect_to future_recipes_url, request.parameters, notice: 'Future link was successfully upranked.' }
        #format.json { head :no_content }
#      else
 #       format.html { redirect_to future_recipes_url, notice: 'Couldnt uprank!' }
  #      format.json { render json: @future_recipe.errors, status: :unprocessable_entity }
   #   end
    #end
  end
  
  def downrank
    @future_recipe.rank = @future_recipe.rank - 1
    
    if @future_recipe.save
      redirect_to future_recipes_path(request.parameters)
    else
      redirect_to future_recipes_url, notice: 'Couldnt downrank!'
    end   
  end
  
private
  def set_state(incoming_state)
    logger.info("SET_STATE: incoming_state = #{incoming_state}")
    if incoming_state == :done
      new_state = "done"
    elsif incoming_state == :discarded
      new_state = "discarded"
    elsif incoming_state == :pending
      new_state = "pending"
    else
      redirect_to future_recipes_url, notice: 'Couldnt change state'
      return
    end
    logger.info("SET_STATE: setting to new state #{new_state}")
    @future_recipe.state = new_state
  
    if @future_recipe.save
      redirect_to future_recipes_path(request.parameters)
    else
      redirect_to future_recipes_url, notice: 'Couldnt change state!'
    end
  end
  


    # Use callbacks to share common setup or constraints between actions.
    def set_future_recipe
      @future_recipe = FutureRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def future_recipe_params
      params.require(:future_recipe)
            .permit(:name, :link, :description, :category_id, :rank, :state, { tag_ids:[] })
    end
    
    def setup_vars
      @is_admin = current_user && current_user.is_admin?
    end
  
      # Confirms an admin user.
    def admin_user
      unless @is_admin
        flash[:danger] = "Must be admin to modify recipes"
        redirect_to(recipes_url) 
      end
    end
  
end

app/helpers/future_recipes_helper.rb
module FutureRecipesHelper
end

app/views/future_recipes/_form.html.erb
<%= form_for(@future_recipe) do |f| %>
  <% if @future_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@future_recipe.errors.count, "error") %> prohibited this future_recipe from being saved:</h2>

      <ul>
      <% @future_recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link, :size => 100 %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.text_field :rank, :size => 10 %>
  </div>
  
  <p>
	<%= f.label :category %>
	<%= f.collection_select(:category_id, Category.order("name"), :id, :name, prompt: true) %>
  </p>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :size => 100%>
  </div>

<div class="checkboxes">
<%c=0%>
  <%= f.collection_check_boxes(:tag_ids, Tag.order(:name), :id, :name) do |cb| %>
	<%=cb.label class:"label-checkbox" do%>
         <%=cb.check_box + cb.text%>
        <%end%>
        <%c=c+1%>
        <%if c == 5%><br/><%c=0%><%end%>
      <%end%>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/future_recipes/_table.html.erb
<%= will_paginate @future_recipes%>
<table class='gridtable'>
  <tr>
  	<th style='width:10%'><%= link_to 'Created',
  									future_recipes_path(@pass_on_search_params.merge(:sort_by => 'sortable_created_at', :descending => '1'))%></th>
    <th style='width:40%'><%= link_to 'Name',
    								future_recipes_path(@pass_on_search_params.merge(:sort_by => 'sortable_name'))%></th>
<!--    <th style='width:50%'>Description</th> -->
    <th style='width:15%'><%= link_to 'Category',
    								future_recipes_path(@pass_on_search_params.merge(:sort_by => 'sortable_category'))%></th>
    <th style='width:15%'><%= link_to 'Link',
    								future_recipes_path(@pass_on_search_params.merge(:sort_by => 'sortable_website'))%></th>
    <th style='width:10%'><%= link_to 'Rank',
    								future_recipes_path(@pass_on_search_params.merge(:sort_by => 'sortable_rank', :descending => '1'))%></th>
    <th style='width:10%'><%= link_to 'State',
    								future_recipes_path(@pass_on_search_params.merge(:sort_by => "state", :descending => '1'))%></th>
    
  </tr>
 
  <% @future_recipes.each do |future| %>
    <tr>
   	  <td><%= future.created_at.strftime("%F") %></td>
   	  <td>
   	  <%if future.discarded?%><s><%= link_to future.name, future_recipe_path(future) %></s>
   	  <%elsif future.done?%><i><%= link_to future.name, future_recipe_path(future) %></i>
   	  <%else%><%= link_to future.name, future_recipe_path(future) %>
   	  <%end%>
   	  </td>
      <!--<td><%= future.description %></td>-->
      <td><%= link_to future.category.name, 
  					future_recipes_path(:search_by_category_id => future.category.id,
  								 :submit_search_by_category_id => '1')  %>
      </td>
      
      <td><%= link_to future.get_link_source, future.link %></td>
      <td><%= future.rank %></td>
      <td><%= future.get_state.capitalize %></td>
    <% if @is_admin %>
      <td><%= link_to 'Uprank', uprank_future_recipe_path(future, @pass_on_sort_params.merge(@pass_on_search_params)) %></td>
      <td><%= link_to 'Downrank', downrank_future_recipe_path(future) %></td>
      <% if future.pending? %>
        <td><%= link_to 'Mark Done', set_state_done_future_recipe_path(future)%></td>
        <td><%= link_to 'Discard', set_state_discarded_future_recipe_path(future)%></td>
      <% else %>
        <td><%= link_to 'Reset State', reset_state_future_recipe_path(future) %></td>
        <td></td>
      <% end %>
      <td><%= link_to 'Edit', edit_future_recipe_path(future) %></td>
      <td><%= link_to 'Delete', future_recipe_path(future),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    </tr>
  <% end %>
</table>


<%= will_paginate @future_recipes %>

app/views/future_recipes/edit.html.erb
<h1>Editing '<%= @future_recipe.name -%>' (<%= link_to "Cancel", future_recipe_path(@future_recipe) -%>)</h1>

<%= render 'form' %>

<%= link_to 'Show', @future_recipe %> |
<%= link_to 'Back', future_recipes_path %>

app/views/future_recipes/index.html.erb
<h1>
	<%if !@filtered_text.blank?%>
Filtered Future Recipes: <%=@filtered_text%>
<%else%>
All Future Recipes
<%end%>
	</h1>
 <%= form_tag(future_recipes_path, :method => "get", id: "search-form") do %>
 <%= hidden_field_tag :sort_by, params[:sort_by] %>

 <div class='boxed_table'>
  <table>
 	<tr>
 		<td>
 			Filter by Name:
 		</td>
		<td>
 			<%= text_field_tag :search_by_future_recipe_name, 
 							params[:search_by_future_recipe_name], 
 							placeholder: "Search Future Recipes by Name", 
 							:autocomplete => :off %>
		</td>
		<td>
			<%= submit_tag "Search", :name => 'submit_search_by_future_recipe_name' %>
		</td>
 	</tr>
 	<tr>
 		<td>
 			Filter by Site:
 		</td>
		<td>
			<%= text_field_tag :search_by_website, 
								params[:search_by_website], 
								placeholder: "Search Future Recipes by Website", 
								:autocomplete => :off %>
		</td>
		<td>
			<%= submit_tag "Search", :name => 'submit_search_by_website' %>
		</td>
 	</tr>
 	
 	 <tr>
 		<td>
 			Filter by Category:
 		</td>
		<td align='right'>
			<%= select_tag(:search_by_category_id, 
							options_from_collection_for_select(
								Category.order("name"), 
								:id, :name, @search_category.id),
							:prompt => '<Select a Category>'
							) %>
		</td>
		<td>
			<%= submit_tag "Search", :name => 'submit_search_by_category_id' %>
		</td>
 	</tr>
 	<tr>
 		<td>
 			Filter by Tag
 		</td>
		<td align='right'>
			<%= select_tag(:search_by_tag_id, 
							options_from_collection_for_select(
								Tag.order("name"), 
								:id, :name, @search_tag.id),
							:prompt => '<Select a Tag>'
							) %>
		</td>
		<td>
			<%= submit_tag "Search", :name => 'submit_search_by_tag_id' %>
		</td>
 	</tr>
 </table>
 <input type="checkbox" name="include_done" value="1">Include Done?<br>
 <input type="checkbox" name="include_discarded" value="1">Include Discarded?<br>
 
 <%= link_to 'Clear Filters', future_recipes_path %>
 </div>
<%end%>
 

<br>
<%= form_tag({:controller => "future_recipes" , :action => "new"} , {:method => :get, id: "add-update-form"}) do %>
 <div class='boxed_table'>
  <table>
 	<tr>
 		<td>
 			Add or Update Link:
 		</td>
		<td>
 			<%= text_field_tag :new_link, 
 							params[:new_link], 
 							placeholder: "New Link to Add", 
 							:autocomplete => :off %>
		</td>
		<td>
			<%= submit_tag "Add or Update", :name => 'add_or_update_link' %>
		</td>
 	</tr>
  </table>
</div>
<%end%>
 							

<%= render 'table' %>

app/views/future_recipes/new.html.erb
<h1>New future_recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', future_recipes_path %>

app/views/future_recipes/show.html.erb
<h1 class='h1-smaller-margin'><%= @future_recipe.name %> 
	<%if @is_admin%>(<%= link_to 'Edit', edit_future_recipe_path(@future_recipe) %>)<%end%>
	</h1>


<% if @future_recipe.category %>
	<%= link_to @future_recipe.category.name,
      			future_recipes_path(:search_by_category_id => @future_recipe.category.id),
      			:class => 'category_tag'
      			%><br/>
<%end%>
<br />
<p>
	<strong>Rank:</strong> <%= @future_recipe.rank%>    
	<% if @is_admin %>
      <%= button_to 'Uprank', uprank_future_recipe_path(@future_recipe), :method => :get %>
      <%= button_to 'Downrank', downrank_future_recipe_path(@future_recipe), :method => :get %>
    <% end %>
  <br/><br/>
	<strong>State:</strong> <%= @future_recipe.get_state.capitalize%><br/>
	<% if @is_admin %>
	<strong>
<%if @future_recipe.state == "pending"%>
  <%= button_to 'Mark as Done', set_state_done_future_recipe_path(@future_recipe), :method => :get %><br/>
  <%= button_to 'Mark as Discarded', set_state_discarded_future_recipe_path(@future_recipe), :method => :get %>
<%else%>
  <%= button_to 'Reset', reset_state_future_recipe_path(@future_recipe), :method =>:get %>
<%end%>
</strong>
<%end%>
</p>
<br />
<p>
  <strong>Description:</strong>
  <%= @future_recipe.description %>
</p>


<% if @future_recipe.tags.count > 0%>
<p>
	<% @future_recipe.tags.each do |tag|%>
		<%= link_to tag.name,
      			future_recipes_path(:search_by_tag_id => tag.id),
      			:class => 'tag_tag'
      			%><br/>
    <%end%>
</p>
<%end%>


<div id="related_links">
	<strong>Link:</strong><br/>
	<ul >
	 <li><%= link_to @future_recipe.link, @future_recipe.link, :target=> '_blank' %></li>
	</ul>
</div>

<br/>
<br/>
<%= link_to 'Edit', edit_future_recipe_path(@future_recipe) %> |
<%= link_to 'Back', future_recipes_path %>