config/routes.rb
Rails.application.routes.draw do
  resources :future_recipes do
      member do
        get 'uprank'
        get'downrank'
        get 'reset_state'
        get 'set_state_done'
        get 'set_state_discarded'
      end
  end

  get 'future_recipes/add_or_update'

  get 'tags/index'

  get 'tags/create'

  get 'tags/show'

  get 'tags/update'

  get 'tags/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'categories/index'

  get 'categories/create'

  get 'categories/show'

  get 'categories/update'

  get 'categories/destroy'

  get 'welcome/index'

  root "welcome#index"

  resources :recipes do
      resources :user_ratings, only: [:new, :create, :update, :destroy]
  end

  resources :ingredients
  resources :categories
  resources :tags
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create,:edit, :update]
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	<% if @recipe && !@recipe.name.blank? %>
  	<%=@recipe.name%>
  	<%else%>
  	Recipes
  	<%end%>
  	</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>


 <% if Rails.env.production? %>
 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58426972-2', 'auto');
  ga('send', 'pageview');

  </script>
  <%end%>
</head>


<body>

<ul class='my_navbar'>
	<li><%= link_to 'Home', root_path %></li>
	<li><%= link_to 'Recipes', recipes_path %></li>
	<li><%= link_to 'Categories', categories_path %></li>
	<li><%= link_to 'Tags', tags_path %></li>
	<li><%= link_to 'Ingredients', ingredients_path %></li>
	<li><%= link_to 'Future Recipes', future_recipes_path %></li>
	<% if logged_in? %>
    <li><%= link_to "Users", users_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        </ul>
      </li>
	<%else%>
	<li><%= link_to "Log in", login_path %></li>
	<%end%>

</ul>

<br />
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<br/>

<h1>THIS HEROKU APPLICATION IS NOW DEPRECATED! Find the new deployment <a href="http://recipes.gerardsweeney.com">HERE</a></h1>
<%= yield %>

 <%= debug(params) if Rails.env.development? %>
 
</body>
</html>